<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>bringup</name>
  <version>0.0.0</version>
  <description>Centralized launch package for the mission workspace</description>
  <maintainer email="user@todo.todo">todo</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Workspace Package Dependencies -->
  <exec_depend>airdrop_planning</exec_depend>
  <exec_depend>target_recognition</exec_depend>
  <exec_depend>simulation</exec_depend>
  <exec_depend>interfaces</exec_depend>

  <!-- External Execution Dependencies -->
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>mavros</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>